apiVersion: v1
kind: Endpoints
metadata:
  name: node-exporter-2
  namespace: lens-metrics
subsets:
  - addresses:
      - ip: 10.244.0.243
        nodeName: lens-desktop-kube
        targetRef:
          kind: Pod
          namespace: lens-metrics
          name: node-exporter-x4jfk
    ports:
      - name: metrics
        port: 9100
        protocol: TCP
