apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: instagram-config
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: instagram-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: instagram-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc # binds this pod to the PVC defined in Pvc.yml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram-api-deployment
  labels:
    app: instagram-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instagram-api
  template:
    metadata:
      labels:
        app: instagram-api
    spec:
      containers:
        - name: instagram-api
          image: instagram-api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: http
          envFrom:
            - configMapRef:
                name: instagram-config # injects DB_HOST, DB_PORT, DB_NAME, FLASK_ENV as env vars
            - secretRef:
                name: instagram-secret # injects DB_USER, DB_PASSWORD as env vars
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15 # Gives Gunicorn 15 seconds to boot before checking health
            periodSeconds: 10 # Checks health every 10 seconds
            timeoutSeconds: 5 # Allows up to 5 seconds for a response instead of the 1s default
            failureThreshold: 3 # Number of failures before marking pod as Unhealthy
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30 # Gives plenty of buffer time before considering a restart
            periodSeconds: 20 # Checks liveness every 20 seconds
            timeoutSeconds: 5 # Allows up to 5 seconds for a response
            failureThreshold: 3 # Restarts the container only after 3 consecutive failures
