apiVersion: apps/v1
kind: Deployment
metadata:
  name: dukaan-app
  namespace: dukaan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dukaan-app
  template:
    metadata:
      labels:
        app: dukaan-app
    spec:
      containers:
        - name: dukaan-api
          image: dukaan-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: dukaan-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: dukaan-config
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: dukaan-config
                  key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: dukaan-config
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dukaan-secret
                  key: DATABASE_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: dukaan-secret
                  key: SECRET_KEY
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: dukaan-secret
                  key: JWT_SECRET_KEY
            # Moved to the bottom so all $(VARIABLES) above are successfully resolved
            - name: DATABASE_URL
              value: "postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)"
          readinessProbe:
            httpGet:
              path: /api/buyer/store/test
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
