apiVersion: v1
kind: Secret 
metadata:
  name: dukaan-secret
  namespace: dukaan
type: Opaque
data:
  DATABASE_PASSWORD: ZHVrYWFuMTIz
  SECRET_KEY: c3VwZXItc2VjcmV0
  JWT_SECRET_KEY: and0LXNlY3JldA== #check this one to be double sure 