apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-api
spec:
  selector:
    matchLabels:
      app: nodejs-api
  template:
    metadata:
      labels:
        app: nodejs-api
    spec:
      containers:
        - name: nodejs-api
          image: node-pvc-image:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: PORT # this name should be same as the name of the environment variable that we are using in our application to read the port number from the environment variable and this is how we can inject the configuration values from the config map into our application using environment variables and this is a common practice to use environment variables to inject configuration values into our application because it allows us to decouple the configuration from the application code and it also allows us to easily change the configuration values without having to rebuild the application image and redeploy the application
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /fetch
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
