#Fetch a base image of nodejs for our basic api-layer 1
FROM node:18-alpine
#now our api also have mongodb so can in one container we can run both node and mongodb but it is not a good practice to run multiple services in one container so we will use docker-compose to run multiple containers for our api and mongodb
#but for the sake of simplicity we will run both node and mongodb in one container but it is not a good practice to run multiple services in one container so we will use docker-compose to run multiple containers for our api and mongodb



#Set the working directory in the container to /app - layer 2
WORKDIR /app

#Copy the package.json and package-lock.json files to the working directory - layer 3
COPY package*.json ./ 
#We dont have to cd into the folder because we have already set the working directory to /app

#Install the dependencies specified in the package.json file - layer 4
RUN npm install

#Copy the rest of the application code to the working directory - layer 5
COPY . .

#Expose the port that the application will run on - layer 6
EXPOSE 3000

#Define the command to run the application - layer 7
CMD ["node", "index.js"]