# =========================
# Builder
# =========================
FROM python:3.12 AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --prefix=/install -r requirements.txt


# =========================
# Runtime
# =========================
FROM python:3.12-slim

WORKDIR /app

COPY --from=builder /install /usr/local

COPY . .

EXPOSE 8000

CMD ["gunicorn", \
  "-w", \
  "4",  \
  "-k", \
  "uvicorn.workers.UvicornWorker", \
  "main:app", \
  "--bind",    \
  "0.0.0.0:8000"]